# language - available by default : en, fr, de, se, cn, es, ja
lang: en
  
# force the music played on join (players can't disable it)
forceJoinMusic: false

# send plugin message when starting/stopping music...
sendMessages: true

# load files asynchronously
asyncLoading: false

# list of worlds where music will be enabled (empty = all)
enabledWorlds: []

# note particles
noteParticles: true

# enable or not action bar messages instead of chat
actionBar: false

# player options gived to new players
defaultPlayerOptions:
  volume: 70
  join: false
  shuffle: false
  particles: false